import { db } from "@/lib/db";
import { notFound } from "next/navigation";
import PrintButton from "@/components/PrintButton"; // سننشئ هذا الزر لاحقاً

export default async function PrintPrescriptionPage({ params }: { params: { id: string } }) {
  const { id } = await params;
  
  // جلب الوصفة + المريض + معلومات العيادة (من الإعدادات)
  const prescription = await db.prescription.findUnique({
    where: { id },
    include: { patient: true }
  });

  const settings = await db.clinicProfile.findUnique({
    where: { id: "settings" } // نفترض أننا سجلنا إعدادات العيادة
  });

  if (!prescription) return notFound();

  return (
    <div className="min-h-screen bg-slate-200 p-8 flex flex-col items-center">
      
      {/* زر الطباعة (يختفي عند الطباعة) */}
      <div className="mb-6 print:hidden">
         <PrintButton />
      </div>

      {/* --- ورقة A4 (التي ستطبع) --- */}
      <div className="bg-white w-[210mm] min-h-[297mm] p-[20mm] shadow-2xl print:shadow-none print:w-full relative text-slate-900">
        
        {/* Header: معلومات الطبيب */}
        <div className="flex justify-between items-start border-b-2 border-slate-900 pb-6 mb-8">
          <div>
            <h1 className="text-2xl font-bold uppercase tracking-wider">{settings?.name || "Dr. Ahmed Benali"}</h1>
            <p className="text-sm font-medium mt-1">General Medicine & Surgery</p>
            <p className="text-xs text-slate-500 mt-1">INPE: 12345678</p>
          </div>
          <div className="text-right text-sm text-slate-600 space-y-1">
            <p>{settings?.address || "123 Medical Blvd, Casablanca"}</p>
            <p>{settings?.phone || "05 22 00 00 00"}</p>
            <p>{settings?.email || "doctor@clinic.com"}</p>
          </div>
        </div>

        {/* Date & Patient Info */}
        <div className="flex justify-between items-end mb-12">
          <div className="text-sm">
            <span className="text-slate-500 block mb-1">Patient:</span>
            <span className="font-bold text-lg">{prescription.patient.firstName} {prescription.patient.lastName}</span>
            <span className="block text-slate-400 text-xs mt-1">Age: {new Date().getFullYear() - 2000} Years</span> 
            {/* (سنقوم بحساب العمر الحقيقي لاحقاً) */}
          </div>
          <div className="text-right">
            <p className="text-slate-500 text-sm">Date: <span className="font-bold text-slate-900">{prescription.createdAt.toLocaleDateString()}</span></p>
            <p className="text-slate-500 text-sm">City: <span className="font-bold text-slate-900">Casablanca</span></p>
          </div>
        </div>

        {/* --- ORDONNANCE --- */}
        <div className="mb-8 text-center">
          <h2 className="text-3xl font-serif font-bold italic border-b border-slate-300 inline-block px-8 pb-2">Ordonnance</h2>
        </div>

        {/* الأدوية */}
        <div className="space-y-6 font-medium text-lg leading-relaxed px-4 min-h-[400px]">
          {/* تحويل النص إلى أسطر */}
          {prescription.medications.split('\n').map((line, index) => (
            <div key={index} className="flex gap-3">
              <span className="font-bold text-slate-400 text-sm mt-1">{index + 1}.</span>
              <span>{line}</span>
            </div>
          ))}
        </div>

        {/* ملاحظات */}
        {prescription.notes && (
            <div className="mt-8 p-4 bg-slate-50 rounded-lg border border-slate-100 text-sm text-slate-600 italic">
                <strong>Note:</strong> {prescription.notes}
            </div>
        )}

        {/* Footer: التوقيع */}
        <div className="absolute bottom-[30mm] right-[30mm] text-center">
          <p className="text-sm font-bold text-slate-400 mb-16">Signature & Cachet</p>
          <div className="w-48 h-0.5 bg-slate-900/20"></div>
        </div>

        {/* Footer Info */}
        <div className="absolute bottom-4 left-0 w-full text-center text-[10px] text-slate-400">
           Generated by MyClinic.pro System
        </div>

      </div>
    </div>
  );
}